---
image: "ruby:2.7"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - gem install bundler -N
  - bundle install -j $(nproc) --path vendor

rubocop:
  script:
    - bundle exec rubocop

pages:
  stage: deploy
  script:
    - gem install yard
    - yard doc -o public/
  artifacts:
    paths:
      - public/
  only:
    - master

# rspec:
#   script:
#   - rspec spec
