---
image: "ruby:2.7"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - gem install bundler -N
  - bundle install -j $(nproc) --path vendor

rubocop:
  script:
    - bundle exec rubocop

pages:
  before_script: []
  script:
    - gem install yard redcarpet
    - yard doc -o public/
  artifacts:
    paths:
      - public/
  only:
    - master

rake:
  script:
    - bundle exec rake
