---
AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - '*.spec'
    - 'Rakefile'
    - 'vendor/**/*'
  NewCops: enable

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'
    - 'app/controllers/concerns/foreman/**/*'
